sbatch b1_2.txt_rMATS_prep.slurm
sbatch b1_3.txt_rMATS_prep.slurm
sbatch b1.txt_rMATS_prep.slurm
sbatch b2_2.txt_rMATS_prep.slurm
sbatch b2_3.txt_rMATS_prep.slurm
sbatch b2.txt_rMATS_prep.slurm
sbatch b3_2.txt_rMATS_prep.slurm
sbatch b3_3.txt_rMATS_prep.slurm
sbatch b3.txt_rMATS_prep.slurm
sbatch b4_2.txt_rMATS_prep.slurm
sbatch b4_3.txt_rMATS_prep.slurm
sbatch b4.txt_rMATS_prep.slurm
sbatch b5_2.txt_rMATS_prep.slurm
sbatch b5_3.txt_rMATS_prep.slurm
sbatch b5.txt_rMATS_prep.slurm
sbatch b6_2.txt_rMATS_prep.slurm
sbatch b6_3.txt_rMATS_prep.slurm
sbatch b6.txt_rMATS_prep.slurm
sbatch b7_2.txt_rMATS_prep.slurm
sbatch b7_3.txt_rMATS_prep.slurm
sbatch b7.txt_rMATS_prep.slurm
sbatch b8_2.txt_rMATS_prep.slurm
sbatch b8_3.txt_rMATS_prep.slurm
sbatch b8.txt_rMATS_prep.slurm
